### ISSUE TITLE
Turn off event listener on esp

### ISSUE THREAD

**Issue by HellRaiserFlight** [timum-viw/socket.io-client#18]
How do I turn off a listener for an event that has already been initialised using .on() ?

**Comment by timum-viw** [comment]
Good question! That's actually not yet implemented. Should be easy though. Just find and delete the corresponding entry in the vector. If you implement it, a pjll request would be nice!

**Comment by HellRaiserFlight** [comment]
I'm a bit of a noob as just started coding with the arduino. Do you mind posting an example/snippet? Thanks!

**Comment by caioaletroca** [comment]
I forked this repo and added the remove event functionality.
I'm glad to contribute, this repo really saves me.

**Comment by timum-viw** [comment]
feature has been added recently.
