### ISSUE TITLE
Concatenate variable int in emit

### ISSUE THREAD

**Issue by OmarGC** [timum-viw/socket.io-client#22]
How to concatenate variable double or int to socket.emit ("event name", "\" CHAIN ​​TO SEND \ "")

Achieve send the normal chain, but the ideal is to send the variable that comes from the sensor.
the question is that I put the structure + String (dataInteger) +
but that sends me error.

example

    `int dis = 88;`
    `webSocket.emit ( "Esp8866_1" , "\" Cadena a enviar "+String(dis)+"\" " );`

**Comment by OmarGC** [comment]
Then I converted to char and sent me this error.
what I want is to send sensor variable by emit

`
/home/omargc/Escritorio/NodeMCU/funcinales/SocketIO_BasicExample/SocketIO_BasicExample.ino: In function 'void setup()':
SocketIO_BasicExample:46: error: invalid operands of types 'const char*' and 'const char [3]' to binary 'operator+'
     webSocket.emit ( "Esp8866_1" , "\" Cisterna: "+char(dis)+"\" " );
                                                              ^
exit status 1
invalid operands of types 'const char*' and 'const char [3]' to binary 'operator+'`

**Comment by timum-viw** [comment]
The concatenation results in a String object. You have to convert it to char *.
Try
`webSocket.emit ( ("Esp8866_1" , "\" Cisterna: "+String(dis)+"\" ").c_str() );`

**Comment by OmarGC** [comment]
Perfect
now he does not send me error
Thank you

**Comment by timum-viw** [comment]
You're welcome!
