### ISSUE TITLE
 Connect 2 esp

### ISSUE THREAD

**Issue by OmarGC** [timum-viw/socket.io-client#24]
I want to communicate 2 esp.
It's possible?
for example I put an esp with the ip 192.168.1.24 and the other in 192.168.1.12
I want to communicate these esp but I do not know which port I should put

` webSocket2.begin ( "192.168.1.12" , 80 , "/socket.io/?transport=websocket" );`

another doubt is the way to send a broadcast
or multicast?
I want to send a message to the server and to the other

**Comment by timum-viw** [comment]
you should just connect both devices to one server and if you have to send messages between them just proxy them through the server by using namespaces or something like that.
