### ISSUE TITLE
Lenght parameter in call back function of socket.on wrong

### ISSUE THREAD

**Issue by ThomasThongCE** [timum-viw/socket.io-client#32]
The length parameter in callback function when using socket.on isn't the length of the socket data. It actually is the lenght of the payload which webSocketEvent receive, which didn't match with the payload length parameter in callback function.
The temporary solution is to change code in the SocketioClient.cpp. In line 31 , replace `trigger(getEventName(msg).c_str(), getEventPayload(msg).c_str(), length);` to `trigger(getEventName(msg).c_str(), getEventPayload(msg).c_str(), strlen(getEventPayload(msg).c_str()));`

Hope this will change in furture commitment. sorry for my English

**Comment by timum-viw** [comment]
nice catch. could you open a pull request?
