### ISSUE TITLE
OTA update support

### ISSUE THREAD

**Issue by jslay88** [timum-viw/socket.io-client#36]
I think it should be possible to perform an OTA update using SocketIO binary transport.

Would this be something that could be implemented or investigated? Would be nice to send FW updates to the ESP devices if they are out of date.

**Comment by timum-viw** [comment]
puh, that would be quite the effort and actually I think that would be more something for another library as it has nothing to do with socket.io. This library would receive the FW through the binary transport as you suggested  and then you pass it on to some other library.

**Comment by jslay88** [comment]
I'm more interested in how it would work (as I am deficient in Arduino) more so that building support into this library. Having said that, if its fairly straight forward enough (not too bloated of a process), I think it would be somewhat useful within this library since it specifically targets ESP devices.
