### ISSUE TITLE
Can't emit

### ISSUE THREAD

**Issue by zenmanenergy** [timum-viw/socket.io-client#4]
I am able to connect to a node.js socket.io server through port 80. I am able to send events from the server to the esp8266, but I cannot seem to emit back to the server. 

It says that it's emitted, but nothing shows up in my server.

I am doing this:
webSocket.emit("whoami", "{ id: \"abc\"}");

It's printing this in the Serial monitor:

[SIoC] add packet 42["whoami",{ id: "abc" }]
[SIoC] packet "42["whoami",{ id: "abc"}]" emitted

**Comment by AndresZeballos** [comment]
Hello @zenmanenergy 

I had the same problem until I changed for: webSocket.emit("whoami", "{ **"**id**"**: "abc"}");
Hope that help

**Comment by timum-viw** [comment]
Yes, I'm quite sure the quotes are necessary. Does this close the issue?

**Comment by timum-viw** [comment]
I'm going to update the readme accordingly

**Comment by zenmanenergy** [comment]
Yes, that was it.
