### ISSUE TITLE
Compiling issue for ATmega 2560

### ISSUE THREAD

**Issue by hafizmuhammadshoaib** [timum-viw/socket.io-client#45]

**Comment by hafizmuhammadshoaib** [comment]
![image](https://user-images.githubusercontent.com/26689197/50051189-818b6e00-012f-11e9-81c8-6c4739fc4062.png)

**Comment by rafalfigura** [comment]
Can you prove source code?

**Comment by hafizmuhammadshoaib** [comment]
I have just included the library and ut shows me this error

**Comment by timum-viw** [comment]
it seems like you are not including / linking the correct std c++ library. What is this "StandardCplusplus.h" you are including?
