### ISSUE TITLE
Disabling Serial Debug

### ISSUE THREAD

**Issue by alternadom** [timum-viw/socket.io-client#46]
Hi,

I would like to disable serial debug on compilation with a flag like NODEBUG_SOCKETIOCLIENT

Is it possible to change this :

```
#define SOCKETIOCLIENT_DEBUG(...) Serial.printf(__VA_ARGS__);
//#define SOCKETIOCLIENT_DEBUG(...)
```
By :
```
#ifndef NODEBUG_SOCKETIOCLIENT
   #define SOCKETIOCLIENT_DEBUG(...) Serial.printf(__VA_ARGS__);
#else
   #define SOCKETIOCLIENT_DEBUG(...)
#endif
```

Thanks,

**Comment by timum-viw** [comment]
sure, sounds reasonable. Would you mind making a pullrequest or shoud I just commit it for you?
cheers!

**Comment by alternadom** [comment]
Hi,

Could you commit it for me, please ?

Thanks,

**Comment by timum-viw** [comment]
done!
