### ISSUE TITLE
socket.on("disconnect", handler) not working

### ISSUE THREAD

**Issue by RobertHolscher** [timum-viw/socket.io-client#47]
In the documentation you write that the disconnect event is triggered when the connection is lost with the server. I am trying to use that with the arduino sketch but the compiler says:
No matching function for call to 'SocketIoClient::on(const char [11], void(&)())'

The call I am using is webSocket.on("disconnect", disconnectevent);

The disconnectevent is the handler 
Am I using it wrongly ?

**Comment by coma0815** [comment]
Do you have a matching function called "disconnectevent"? 
In my sketch it would look like this:

`void disconnected(const char * payload, size_t length) {
    // do something when disconnected....
}

webSocket.on("disconnect", disconnected);`

**Comment by RobertHolscher** [comment]
Thank you, forgot to put in the (const char * payload, size_t length), overlooked that. Thanks for your reply

**Comment by RobertHolscher** [comment]
It compiles ok now , case closed
