### ISSUE TITLE
[SIoC] Disconected error path

### ISSUE THREAD

**Issue by MaudorElConquistador** [timum-viw/socket.io-client#51]
It's my first time opening an issue.
The problem is that my wemos d1 is not connecting to the path on the server
Here is my code from wemos
![image](https://user-images.githubusercontent.com/37784330/56979631-ddcfb700-6b3f-11e9-913c-ac218ce43e0c.png)
And here is the server code in Node js
![image](https://user-images.githubusercontent.com/37784330/56979793-34d58c00-6b40-11e9-9ebf-b915bf30a2c7.png)
If everything was fine the console would print the socket id

**Comment by aswinva** [comment]
this library can't be used to connect to custom nameSpaces. you are using /client and / thermo as custom nameSpaces
