### ISSUE TITLE
SocketIOClient is eating heap like hungry monster

### ISSUE THREAD

**Issue by RobertHolscher** [timum-viw/socket.io-client#56]
Hi I have succesfully implemented the Socket.io library into my ESP8266. I have noticed that when I am using and initializing the SocketIoClient, the heap is reduced from 20000 to 4500 
When I am then receiving some calls and do some other computation, the heap is dangerously low and causing resets.

Why does it eat away so much heap by default and can this be reduced somewhere in the library ?
Your help is appreciated

**Comment by lulersoft** [comment]
when emit message ,a memory leak occurs, it is normal to receive the message，For unknown reasons, please give me some advice。It seems that the message package sent has not been destroyed。

**Comment by lulersoft** [comment]
in void SocketIoClient::loop() ,add this code: std::vector<String>(_packets).swap(_packets):

	if(millis() - _lastPing > PING_INTERVAL) {
		_webSocket.sendTXT("2");
		_lastPing = millis();
		std::vector<String>(_packets).swap(_packets);//DC
	}

**Comment by GowthamGottimukkala** [comment]
> Hi I have succesfully implemented the Socket.io library into my ESP8266. I have noticed that when I am using and initializing the SocketIoClient, the heap is reduced from 20000 to 4500
> When I am then receiving some calls and do some other computation, the heap is dangerously low and causing resets.
> 
> Why does it eat away so much heap by default and can this be reduced somewhere in the library ?
> Your help is appreciated

Hey! I am new to this. How can I check my heap?
Any help is appreciated
