### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by uriel-frankel** [timum-viw/socket.io-client#57]
I am trying to run the example on the Arduino IDE and I get this: fatal error: "WebSocketsClient.h: No such file or directory #include <WebSocketsClient.h>"

**Comment by coma0815** [comment]
Did you install the websocket library as well as written in the readme-docs? 
2. Install WebSockets by Markus Sattler
Then it should compile just fine..
Regards, Constantin

**Comment by uriel-frankel** [comment]
Oh thanks!
