### ISSUE TITLE
Missing <WebSocketsClient.h>

### ISSUE THREAD

**Issue by llopez** [timum-viw/socket.io-client#63]
The program does not compile:
It says:
```/Users/luigi/Documents/Arduino/libraries/SocketIoClient/SocketIoClient.h:7:30: fatal error: WebSocketsClient.h: No such file or directory```

I guess it depends on another library or there is a missing header file.

**Comment by coma0815** [comment]
Please install the library “WebSockets” by Markus Sattler as written in the readme file..

**Comment by llopez** [comment]
Yes. That was the problem.

Thanks

**Comment by ShovonSaha** [comment]
I have installed the library but still facing the same issue :/

**Comment by bishnu6** [comment]
thank you

**Comment by oblonka** [comment]
solve it,ths
