### ISSUE TITLE
Can't connect my server

### ISSUE THREAD

**Issue by 0x587** [timum-viw/socket.io-client#64]
my mcu code:
![批注 2020-01-16 153023](https://user-images.githubusercontent.com/40025941/72502857-4cdb7000-3875-11ea-8ca1-cb8e687261d8.png)

> webSocket.begin("192.168.0.203", 5000);

I use flask server.
![批注 2020-01-16 153213](https://user-images.githubusercontent.com/40025941/72502894-6381c700-3875-11ea-96ed-6b5b4a3d394e.png)

And I use js connect my server success,so ithink my server is working.
![批注 2020-01-16 153250](https://user-images.githubusercontent.com/40025941/72502954-8ca25780-3875-11ea-9d22-dccaf349c44d.png)

**Comment by 0x587** [comment]
## HI,anyone there??

**Comment by 3omer** [comment]
this might help [559](https://github.com/Links2004/arduinoWebSockets/issues/559#issuecomment-680320792)
