### ISSUE TITLE
Send mac address to server

### ISSUE THREAD

**Issue by qiwalker** [timum-viw/socket.io-client#66]
HI, 

can i send esp8266 mac address using socket.io to server ?

webSocket.emit("input1", macadrress);

thanks
Rizki

**Comment by shiro-noname** [comment]
I think if you change it to String. It will be easier

**Comment by AmineGm73** [comment]
I found this about getting network interfaces : [Node.Js os.networkInterfaces()](https://nodejs.org/dist/latest-v12.x/docs/api/os.html#os_os_networkinterfaces)
