### ISSUE TITLE
Error: read ECONNRESET with Node.JS Socket server

### ISSUE THREAD

**Issue by nvomedia** [timum-viw/socket.io-client#73]
Hi,

I'm trying to connect the client to a server at my localhost (and if that works to a live server).
I have used Node.JS and Socket.IO for that server and it's working in my browser, now I try to connect to the same server using my Wemos D1 Mini.

I have installed the library, and my code compiles. But I can't connect to my server. I have tried almost every possibility but the only message I get is ``[WSc] Disconnected!``

Based on the code from the example I have now this:

```
webSocket.begin("127.0.0.1", 5000, "/socket.io/?EIO=3&transport=websocket");
webSocket.onEvent(webSocketEvent);
webSocket.setReconnectInterval(5000);
webSocket.enableHeartbeat(15000, 3000, 2);
```
I have also tried ``localhost`` and no path and the default path. My local server is running port 5000 and as I said, that is working in my browser. In my network console from my browser I see that the webservice requests also are sended to that address.

How can I get this to work?

**Comment by nvomedia** [comment]
I made a fault in here. From the side of the ESP8266 the host is of course not 127.0.0.1 but the internal IP of the router. 
So that is fixed.

But now I get an `Error: read ECONNRESET` in Node.JS after the ESP is connected. I did a few searches about that, and it looks that that is because an incorrect close of the connection. 
Did someone else had this problem in combination with a Node.JS server?

**Comment by nvomedia** [comment]
I used the wrong example... my bad.. I had to use the SocketIO and now I can connect to the server!

**Comment by gonzaloeiza** [comment]
Hey, how did you managed to solve this problem? I have a similar problem with my node js server. When de ESP is connected an ECONNRESET error appears and I can´t solve it.
Here is the  code where I try to stablish the connection:
`    webSocket.begin("192.168.1.76", 8080);
    webSocket.onEvent(webSocketEvent);
`
