### ISSUE TITLE
Complie Error 

### ISSUE THREAD

**Issue by xdubx** [timum-viw/socket.io-client#77]
home/hp/Arduino/libraries/SocketIoClient/SocketIoClient.cpp:41:27: error: 'hexdump' was not declared in this scope
    hexdump(payload, length);
                           ^
I complied it for esp32. Uncomment it and it work again.

**Comment by coma0815** [comment]
Take a look at this issue: https://github.com/timum-viw/socket.io-client/issues/15

**Comment by xdubx** [comment]
Okey. Seems to be solved.

**Comment by aranchuzz** [comment]
How did you solve it?

**Comment by dlowrance** [comment]
I was able to get it to compile by commenting out this line:
41 //hexdump(payload, length);

In this file:
C:\Users\YourUsername\Documents\Arduino\libraries\SocketIoClient\SocketIoClient.cpp

I'm new to C++ but I assume this isn't critical to it's functionality as it looks like a logging utility.

Edit:
After looking deeper into this thread that is a confirmed fix. But I'll leave it here for the tl;dr
