### ISSUE TITLE
When the socket is connected? 

### ISSUE THREAD

**Issue by vinii8817** [timum-viw/socket.io-client#8]
Thanks for the simplified library, this helped a lot in my projects in my house ^^

How can I tell when the socket is connected? 
I want to check this before doing an emit().
I searched in library, but could not make this modification. 
Can you help me with this?

**Comment by timum-viw** [comment]
sure. there is a "connect" event once the client connects. you can subscribe to it by calling `ws.on("connect", cb)`. It is documented in the readme.
