### ISSUE TITLE
Connected on Flask SocketIO Server but still disconnected on esp8266

### ISSUE THREAD

**Issue by leond08** [timum-viw/socket.io-client#83]
SOCKETIO server: Flask SocketIO

I encountered a weird error when connecting to my flask socketio server
On my flask socketio server it says "connected" but on my esp8266
the connection is "disconnected". 
The error is "[SIoC] Disconnected!"

Here is my code:

SocketIoClient socketIO;
socketIO.begin("192.168.0.1", 5001, "/socket.io/?transport=polling");
socketIO.on("event", handleWebSocket);
socketIO.on("connect", handleWeSocketConnected);

Flask:

@socketio.on('event')
def event_message(message):
    logging.info(message)

@socketio.on('connect')
def event_connect():
    mac = get_mac_address(ip=request.remote_addr, network_request=False)
    emit('event', {'data': 'connected', 'mac': mac}, broadcast=False)

@socketio.on('disconnect')
def event_disconnect():
    emit('event', {'data': "disconnected", 'mac': ""}, broadcast=False

On my Flask server It say's connected:
f497ae608950497cb85403b54e3d9c51: Sending packet OPEN data {'sid': 'f497ae608950497cb85403b54e3d9c51', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
emitting event "event" to f497ae608950497cb85403b54e3d9c51 [/]
f497ae608950497cb85403b54e3d9c51: Sending packet MESSAGE data 2["event",{"data":"connected","mac":"fc:f5:c4:94:7c:7f"}]

But on nodemcu:
I 'am disconnected.

**Comment by 3omer** [comment]
Had same problem:
Here what I done to solve it:
1- https://stackoverflow.com/a/62774684
2- Run the server as mentioned in the docs "python server.py" for example. Not by flask run
3- emit strings like this:  webSocket.emit("from_esp", "\"Hello from esp\""),
