### ISSUE TITLE
Crash Using <SocketIoClient.h> with  <TinyGsmClient.h>

### ISSUE THREAD

**Issue by holajuanfe** [timum-viw/socket.io-client#84]
Hi, 

My code works perfectly until i run          webSocket.loop();

In that moment i got this error: 

home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x4008ae1d on core 1

Backtrace: 0x4008ea1c:0x3ffb18e0 0x4008ec4d:0x3ffb1900 0x4008ae1d:0x3ffb1920 0x4012181e:0x3ffb1960 0x40121a1e:0x3ffb1980 0x40113e80:0x3ffb19a0 0x40113ee9:0x3ffb19c0 0x40111086:0x3ffb19e0 0x4010ff10:0x3ffb1a00 0x40113704:0x3ffb1a40 0x400d6bf5:0x3ffb1a60 0x400d65aa:0x3ffb1ab0 0x400d6409:0x3ffb1ae0 0x400d3cf3:0x3ffb1b00 0x400d329e:0x3ffb1b20 0x400d37dc:0x3ffb1f60 0x400d9b4b:0x3ffb1fb0 0x4008b131:0x3ffb1fd0

Rebooting...

Here is my full code 

`

const char apn[]      = "movistar.es"; // APN 
const char gprsUser[] = "MOVISTAR"; // GPRS User
const char gprsPass[] = "MOVISTAR"; // GPRS Password

/*
const char apn[]      = "lowi.private.omv.es"; // APN
const char gprsUser[] = ""; // GPRS User
const char gprsPass[] = ""; // GPRS Password
*/

// SIM card PIN (leave empty, if not defined)
const char simPIN[]   = ""; 

// Server details
const char server[] = "46.101.202.197";
const int  port = 3000;
const char resource[] = "/";

// TTGO T-Call pins
#define MODEM_RST            5
#define MODEM_PWKEY          4
#define MODEM_POWER_ON       23
#define MODEM_TX             27
#define MODEM_RX             26
#define I2C_SDA              21
#define I2C_SCL              22

// Set serial for debug console (to Serial Monitor, default speed 115200)
#define SerialMon Serial
// Set serial for AT commands (to SIM800 module)
#define SerialAT Serial1

// Configure TinyGSM library
#define TINY_GSM_MODEM_SIM800      // Modem is SIM800
#define TINY_GSM_RX_BUFFER   1024  // Set RX buffer to 1Kb

// Define the serial console for debug prints, if needed
//#define DUMP_AT_COMMANDS

#include <Wire.h>
#include <TinyGsmClient.h>

#ifdef DUMP_AT_COMMANDS
  #include <StreamDebugger.h>
  StreamDebugger debugger(SerialAT, SerialMon);
  TinyGsm modem(debugger);
#else
  TinyGsm modem(SerialAT);
#endif

// I2C for SIM800 (to keep it running when powered from battery)
TwoWire I2CPower = TwoWire(0);

#include <Arduino.h>
#include <SocketIoClient.h>

SocketIoClient webSocket;

// TinyGSM Client for Internet connection
TinyGsmClient GSMclient(modem);

#define uS_TO_S_FACTOR 1000000     /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP  3600        /* Time ESP32 will go to sleep (in seconds) 3600 seconds = 1 hour */

#define IP5306_ADDR          0x75
#define IP5306_REG_SYS_CTL0  0x00

bool setPowerBoostKeepOn(int en){
  I2CPower.beginTransmission(IP5306_ADDR);
  I2CPower.write(IP5306_REG_SYS_CTL0);
  if (en) {
    I2CPower.write(0x37); // Set bit1: 1 enable 0 disable boost keep on
  } else {
    I2CPower.write(0x35); // 0x37 is default reg value
  }
  return I2CPower.endTransmission() == 0;
}

#include "ArduinoJson.h"
const char* gName = "Carlos";
const char* deviceName = "GateWay Siverus";

/******************************/

void event(const char * payload, size_t length) {
  SerialMon.printf("got message: %s\n", payload);
}

/******************************/

void setup() {
  // Set serial monitor debugging window baud rate to 115200
  SerialMon.begin(115200);

  SerialMon.setDebugOutput(true);

  // Start I2C communication
  I2CPower.begin(I2C_SDA, I2C_SCL, 400000);

  // Keep power when running from battery
  bool isOk = setPowerBoostKeepOn(1);
  SerialMon.println(String("IP5306 KeepOn ") + (isOk ? "OK" : "FAIL"));

  // Set modem reset, enable, power pins
  pinMode(MODEM_PWKEY, OUTPUT);
  pinMode(MODEM_RST, OUTPUT);
  pinMode(MODEM_POWER_ON, OUTPUT);
  digitalWrite(MODEM_PWKEY, LOW);
  digitalWrite(MODEM_RST, HIGH);
  digitalWrite(MODEM_POWER_ON, HIGH);

  // Set GSM module baud rate and UART pins
  SerialAT.begin(115200, SERIAL_8N1, MODEM_RX, MODEM_TX);
  delay(3000);

  // Restart SIM800 module, it takes quite some time
  // To skip it, call init() instead of restart()
  SerialMon.println("Initializing modem...");
  modem.restart();
  // use modem.init() if you don't need the complete restart

  // Unlock your SIM card with a PIN if needed
  if (strlen(simPIN) && modem.getSimStatus() != 3 ) {
    modem.simUnlock(simPIN);
  }

   
  SerialMon.print("Connecting to APN: ");
  SerialMon.print(apn);
  if (!modem.gprsConnect(apn, gprsUser, gprsPass)) {
    SerialMon.println(" fail");
  }
  else {
    SerialMon.println(" OK");
    
    SerialMon.print("Connecting to ");
    SerialMon.print(server);
    if (!GSMclient.connect(server, port)) {
      SerialMon.println(" fail");
    }
    else {
      SerialMon.println(" OK");

      SerialMon.println("starting WebSocket client");
    
      webSocket.on("event", event);
      webSocket.begin(server, port);

      SerialMon.println("End Starting WebSocket client");

poster();

      SerialMon.println("Fin del Loop");
    }
  }
  
  }

void poster(){
  for (;;) {

    char bbuffer[500];
    StaticJsonDocument<500> contentdata;

    contentdata["Gid"] = gName;
    contentdata["blE"] = "Casas Amarillas";
    contentdata["Dato"] = deviceName;

    serializeJson(contentdata, bbuffer);
    webSocket.emit("newGateway", bbuffer);
 
    // wait 5 seconds
    delay(5000);
  }

  Serial.println("disconnected");

  
  }

void loop() {
  
         webSocket.loop();

}`

Thanks!

**Comment by Sakthivelgovindan** [comment]
Now I'm getting the same issue. Can anyone please help? How to use TinyGsmClient.h with SocketIOClient.h
