### ISSUE TITLE
Manual Disconnect not found.

### ISSUE THREAD

**Issue by sarthakz9** [timum-viw/socket.io-client#9]
How can i disconnect manually? 
something like this `webSocket.disconnect();`

Please note WebSocketsClient library has a definition for disconnect. If you could guide me, I would like to contribute to this library.

**Comment by timum-viw** [comment]
You are right. This method is not implemented yet. But as you said yourself it should be as easy as wrapping `WebSocketsClient.disconnect` into an own method.
Do you want to write it an make a pull request, or should I just quickly add it in?
Thanks for your contribution!

**Comment by sarthakz9** [comment]
Yes, I want to contribute. But, I have never made a pull request before. so it may take some time.
