### ISSUE TITLE
socket.io version

### ISSUE THREAD

**Issue by AbrarChowdhury** [timum-viw/socket.io-client#95]
what socket.io version is being used in this library?
according to the socket.io documentation socket.io version of the client needs to be same as the socket.io version of the server. 

I have node.js backend and I am unsure about which version of socket.io needs to installed there

**Comment by dipan29** [comment]
Following this, I tried with socket io 3 on node backend, but it didn't connect with the ESP8266.

**Comment by timum-viw** [comment]
#91 This was already mentioned here. For now only socket.io v2 is supported.
