### ISSUE TITLE
Compilation Error. 

### ISSUE THREAD

**Issue by rodentskie** [timum-viw/socket.io-client#96]
Good day,

I used the example of WebSockets by Markus Sattler the WebSocketClientSocketIO and yes it can connect to my server.

![image](https://user-images.githubusercontent.com/49242131/104085941-3d2b1780-528e-11eb-86a5-383082a7c941.png)

But when I'm using the example from this library, I can't even compile my code. Here is the error I get.

![image](https://user-images.githubusercontent.com/49242131/104085949-559b3200-528e-11eb-96de-3b55812fc161.png)

I comment and uncomment some stuff but all of this is from the example.
I added -lstdc++ already in the platform of esp8266, and install libraries.
Please help Sir / Ma'am.

```
#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <SocketIoClient.h>

#define USE_SERIAL Serial

ESP8266WiFiMulti WiFiMulti;
SocketIoClient webSocket;

void event(const char * payload, size_t length) {
  USE_SERIAL.printf("got message: %s\n", payload);
}

void setup() {
  USE_SERIAL.begin(115200);

  USE_SERIAL.setDebugOutput(true);

  USE_SERIAL.println();
  USE_SERIAL.println();
  USE_SERIAL.println();

  for (uint8_t t = 4; t > 0; t--) {
    USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
    USE_SERIAL.flush();
    delay(1000);
  }

  WiFiMulti.addAP("OnePiece", "dFGSJZ8476");

  while (WiFiMulti.run() != WL_CONNECTED) {
    delay(100);
  }
//
//
//  webSocket.begin("192.168.1.34", 5000);
//  webSocket.on("event", event);
  // use HTTP Basic Authorization this is optional remove if not needed
  //  webSocket.setAuthorization("username", "password");
}

void loop() {
  webSocket.loop();
}
```

Here is the code.

**Comment by kevinlhoste** [comment]
hi , 
I got exctly the same error how did you solve it ?
Thanks

**Comment by rodentskie** [comment]
> hi ,
> I got exctly the same error how did you solve it ?
> Thanks

Go to the library's .cpp file and remove the beginSSL block of code. That's how I fixed the issue.
